services:
  dialyra_flask:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: dialyra-flask
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "5001:5000"
    depends_on:
      - postgres
      - redis
      - dialyra_asterisk
    volumes:
      - ./:/app
      - ./storage/audio:/data/audio
      - ./storage/recordings:/data/recordings
    networks:
      - dialyra-net

  dialyra_fastagi:
    build:
      context: .
      dockerfile: fastagi/Dockerfile
    container_name: dialyra-fastagi
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - postgres
      - redis
    command: ["python", "fastagi/server.py"]
    ports:
      - "127.0.0.1:4573:4573"
    volumes:
      - ./:/app
      - ./storage/audio:/data/audio
      - ./storage/recordings:/data/recordings
    networks:
      - dialyra-net

  dialyra_asterisk:
    build:
      context: .
      dockerfile: asterisk/Dockerfile
    container_name: dialyra-asterisk
    restart: unless-stopped
    ports:
      - "5060:5060/udp"
      - "5060:5060/tcp"
      - "127.0.0.1:5038:5038"
      - "10000-10100:10000-10100/udp"
    volumes:
      - ./asterisk:/etc/asterisk
      - ./storage/audio:/var/lib/asterisk/sounds/custom
      - ./storage/recordings:/var/spool/asterisk/monitor
    networks:
      - dialyra-net

  postgres:
    image: postgres:15
    container_name: dialyra-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dialyra-net

  redis:
    image: redis:7
    container_name: dialyra-redis
    restart: unless-stopped
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - dialyra-net

volumes:
  postgres_data:
  redis_data:

networks:
  dialyra-net:
