services:
  dialyra_flask:
    environment:
      AMI_HOST: ${AMI_HOST:-138.252.125.100}
      AMI_PORT: ${AMI_PORT:-5038}
      AMI_USERNAME: ${AMI_USERNAME:-admin}
      AMI_SECRET: ${AMI_SECRET:-dialyra123}
      AMI_TIMEOUT: ${AMI_TIMEOUT:-5}
    ports:
      - "5000:5000"
