[settings]
ps_endpoints => pgsql,dialyra_db,ps_endpoints
ps_auths => pgsql,dialyra_db,ps_auths
ps_aors => pgsql,dialyra_db,ps_aors
ps_registrations => pgsql,dialyra_db,ps_registrations
ps_endpoint_id_ips => pgsql,dialyra_db,ps_endpoint_id_ips

