[transport-udp]
type=transport
protocol=udp
bind=0.0.0.0:5060


[bdwebs-auth]
type=auth
auth_type=userpass
username=09617179124
password=hrsb8zaw8e7


[bdwebs-aor]
type=aor
contact=sip:202.40.176.2:5060


[bdwebs-endpoint]
type=endpoint
transport=transport-udp
context=outbound

disallow=all
allow=ulaw,alaw

outbound_auth=bdwebs-auth
aors=bdwebs-aor

from_user=09617179124
from_domain=202.40.176.2

direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes